apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: spring-boot
    namespace: hello-spring
    team: quan-team
  name: hello-spring-kubernetes
spec:
  replicas: 2
  selector:
    matchLabels:
      app.kubernetes.io/name: spring-boot
  template:
    metadata:
      labels:
        app.kubernetes.io/name: spring-boot
    spec:
      containers:
        - name: hello-spring-kubernetes
          image: com.quan/demo-spring:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8080
          resources:
            limits:
              cpu: 100m
              memory: 150Mi
            requests:
              cpu: 50m
              memory: 50Mi
---
apiVersion: v1
kind: Service
metadata:
  name: hello-service
spec:
  selector:
      app.kubernetes.io/name: spring-boot
  ports:
     - name: port-80
       protocol: TCP
       port: 80
       targetPort: 8080
  type: LoadBalancer


